#!/bin/bash

## REPO PATH
BACKUP_PATH=$HOME/backup_duplicity

## REPO WITH FILES AND COPY-LINKS
SRC_PATH=$BACKUP_PATH/backup

## LOG PATH DIRECTORY
LOG_PATH=$BACKUP_PATH/log

## MAKE FULL BACKUP EVERY TIME
FULL_BACKUP_TIME=1M

## DELETE BACKUP AFTER TIME
REMOVE_BACKUP_TIME=6M
